project:
  type: website

website:
  title: "Joe Sferra's Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - portfolio.qmd
      - blog.qmd
    right: 
      - icon: github
        href: https://www.github.com/jdsferra
      - icon: linkedin
        href: https://www.linkedin.com/in/joe-sferra
format:
  html:
    theme: lux
    css: styles.css
    toc: true



